name: Go

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        run: go build -v ./...

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Print vars
        run: |
          export
          go env

      - name: Test
        run: go test -v ./...

  notify:
    needs:
      - build
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Telegram Notify
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            ${{ github.actor }} ${{ github.event.action }} PR ${{ github.event.number }}:
            [_${{ github.event.pull_request.title }}_](${{ github.event.pull_request.html_url }})
