name: Go

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        run: go build -v ./...

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Print vars
        run: |
          export
          go env

      - name: Test
        run: go test -v ./...

  lint:
    needs:
      - build
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
      - uses: actions/checkout@v2
      - name: golangci-lint
      - uses: golangci/golangci-lint-action@v3.1.0
        with:
          version: latest

  notify:
    needs:
      - build
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Notify
        uses: KlyuchnikovV/telegram-notify@v0.1.9
        if: always()
        with:
          chat_id: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          status: ${{ job.status }}
          parse_mode: markdown
          disable_links_preview: true
