name: Go

on: [push]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify on success
        uses: KlyuchnikovV/telegram-notify@v0.1.5
        if: always()
        with:
          chat_id: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          parse_mode: markdown
