name: Go

on: [push]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify on success
        uses: KlyuchnikovV/telegram-notify@v0.1.4
        if: always()
        with:
          chat_id: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          parse_mode: markdown
          message: |
            ✅ Build [#${{ github.run_number }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) of "[${{ github.repository }}](${{ github.server_url }}/${{ github.repository }})" ${{ github.action_status }}.

            📝 Commit by ${{ github.actor }} on ${{ github.ref_name }}:
            ${{ github.event.head_commit.message }}
